services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # Para ver el dashboard en http://localhost:15672

    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mysecurepassword

  saludador:
    build: .
    container_name: saludador
    depends_on:
      - rabbitmq

  api:
    build: .
    container_name: api
    command: ["node", "api.js"]
    depends_on:
      - rabbitmq
